import type { DispatchIntake } from '@/types/intake';
import type { InternalNote } from '@/types/note';
import type { ActivityLog } from '@/types/activity';
import type { Profile } from '@/types/profile';

/**
 * In-memory demo store. Active when Supabase env vars are missing.
 * Mirrors the Supabase schema so the rest of the app doesn't care which source is active.
 */

const nowIso = () => new Date().toISOString();
const ago = (mins: number) => new Date(Date.now() - mins * 60_000).toISOString();

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'demo-user',
    full_name: 'Demo Dispatcher',
    email: 'demo@dispatch.local',
    role: 'admin',
    avatar_url: null,
    created_at: nowIso(),
    updated_at: nowIso(),
  },
  {
    id: 'u-morgan',
    full_name: 'Morgan Lee',
    email: 'morgan@dispatch.local',
    role: 'dispatcher',
    avatar_url: null,
    created_at: nowIso(),
    updated_at: nowIso(),
  },
  {
    id: 'u-sam',
    full_name: 'Sam Patel',
    email: 'sam@dispatch.local',
    role: 'sales_rep',
    avatar_url: null,
    created_at: nowIso(),
    updated_at: nowIso(),
  },
];

export const MOCK_INTAKES: DispatchIntake[] = [
  {
    id: 'intake-001',
    created_at: ago(20),
    updated_at: ago(20),
    caller_name: 'John Smith',
    caller_phone: '5551234567',
    caller_email: 'johnsmith@example.com',
    company_name: 'Smith Logistics',
    company_id: null,
    pickup_location: 'Atlanta, GA',
    delivery_location: 'Nashville, TN',
    load_type: 'Dry Van',
    trailer_type: '53 ft dry van',
    weight: '18000 lbs',
    pickup_date: '2026-04-19',
    urgency: 'high',
    special_instructions: 'Needs pickup before noon.',
    call_summary:
      'Caller requested dispatch help for a same-day dry van load from Atlanta to Nashville.',
    transcript:
      'Agent: Thanks for calling Dispatch Intake. How can I help?\nCaller: Hi, I need a truck today, dry van, Atlanta to Nashville, 18,000 lbs, must pick before noon.\nAgent: Got it — I will route this to a dispatcher now.',
    recommended_action: 'Confirm pickup window and quote rate within 30 minutes.',
    missing_fields: [],
    priority_score: 82,
    intake_status: 'new',
    source: 'elevenlabs_dispatch_agent',
    assigned_to: null,
    elevenlabs_call_id: 'elv_call_001',
    make_execution_id: 'make_exec_001',
    call_timestamp: ago(20),
  },
  {
    id: 'intake-002',
    created_at: ago(120),
    updated_at: ago(120),
    caller_name: 'Dana Wu',
    caller_phone: '5559870011',
    caller_email: 'dana@coldchain.io',
    company_name: 'ColdChain Freight',
    company_id: null,
    pickup_location: 'Dallas, TX',
    delivery_location: 'Phoenix, AZ',
    load_type: 'Reefer',
    trailer_type: '53 ft reefer',
    weight: '32000 lbs',
    pickup_date: '2026-04-21',
    urgency: 'critical',
    special_instructions: 'Must maintain 34F, driver must have PPE.',
    call_summary:
      'Temperature-sensitive pharma load. Caller needs dedicated reefer with team drivers.',
    transcript:
      'Agent: How cold does this need to stay?\nCaller: Thirty-four degrees, non-negotiable. Pharma product, team drivers required.\nAgent: Understood — marking critical.',
    recommended_action: 'Flag for ops manager. Confirm team drivers available.',
    missing_fields: ['insurance_certificate'],
    priority_score: 95,
    intake_status: 'new',
    source: 'elevenlabs_dispatch_agent',
    assigned_to: 'u-morgan',
    elevenlabs_call_id: 'elv_call_002',
    make_execution_id: 'make_exec_002',
    call_timestamp: ago(120),
  },
  {
    id: 'intake-003',
    created_at: ago(1440),
    updated_at: ago(900),
    caller_name: 'Marcus Hall',
    caller_phone: '5553330099',
    caller_email: null,
    company_name: 'Hall Brothers Hauling',
    company_id: null,
    pickup_location: 'Kansas City, MO',
    delivery_location: 'Denver, CO',
    load_type: 'Flatbed',
    trailer_type: '48 ft flatbed',
    weight: '44000 lbs',
    pickup_date: '2026-04-22',
    urgency: 'normal',
    special_instructions: 'Tarp required.',
    call_summary: 'Standard flatbed move. Caller has worked with us twice previously.',
    transcript:
      'Agent: Do you need tarping?\nCaller: Yeah, steel coils, 6-axle tarp.\nAgent: On it.',
    recommended_action: 'Quote by EOD. Possible repeat customer discount.',
    missing_fields: ['caller_email'],
    priority_score: 60,
    intake_status: 'contacted',
    source: 'elevenlabs_dispatch_agent',
    assigned_to: 'u-sam',
    elevenlabs_call_id: 'elv_call_003',
    make_execution_id: 'make_exec_003',
    call_timestamp: ago(1440),
  },
  {
    id: 'intake-004',
    created_at: ago(240),
    updated_at: ago(200),
    caller_name: 'Priya Desai',
    caller_phone: '5557772244',
    caller_email: 'priya@novaship.com',
    company_name: 'NovaShip',
    company_id: null,
    pickup_location: 'Newark, NJ',
    delivery_location: 'Boston, MA',
    load_type: 'LTL',
    trailer_type: 'Box truck',
    weight: '3500 lbs',
    pickup_date: '2026-04-18',
    urgency: 'high',
    special_instructions: 'Liftgate needed at delivery.',
    call_summary:
      'Short-haul LTL with liftgate requirement. Asking about same-day quote.',
    transcript:
      'Agent: Any special equipment?\nCaller: Yes, liftgate at delivery.\nAgent: Noted.',
    recommended_action: 'Provide liftgate-qualified carrier list. Respond with quote today.',
    missing_fields: [],
    priority_score: 74,
    intake_status: 'quoted',
    source: 'elevenlabs_dispatch_agent',
    assigned_to: 'u-morgan',
    elevenlabs_call_id: 'elv_call_004',
    make_execution_id: 'make_exec_004',
    call_timestamp: ago(240),
  },
  {
    id: 'intake-005',
    created_at: ago(2880),
    updated_at: ago(2400),
    caller_name: "Chris O'Brien",
    caller_phone: '5554442211',
    caller_email: 'chris@obrien.co',
    company_name: "O'Brien Hauling",
    company_id: null,
    pickup_location: 'Seattle, WA',
    delivery_location: 'Portland, OR',
    load_type: 'Dry Van',
    trailer_type: '26 ft box',
    weight: '9000 lbs',
    pickup_date: '2026-04-23',
    urgency: 'low',
    special_instructions: null,
    call_summary: 'Customer wants to schedule recurring weekly runs.',
    transcript:
      'Agent: How often do you need this move?\nCaller: Every Friday for the next three months.',
    recommended_action: 'Schedule follow-up next Monday to confirm contract.',
    missing_fields: [],
    priority_score: 45,
    intake_status: 'booked',
    source: 'elevenlabs_dispatch_agent',
    assigned_to: 'u-sam',
    elevenlabs_call_id: 'elv_call_005',
    make_execution_id: 'make_exec_005',
    call_timestamp: ago(2880),
  },
  {
    id: 'intake-006',
    created_at: ago(30),
    updated_at: ago(30),
    caller_name: 'Jordan Peters',
    caller_phone: '5552228800',
    caller_email: null,
    company_name: null,
    company_id: null,
    pickup_location: null,
    delivery_location: 'Miami, FL',
    load_type: null,
    trailer_type: null,
    weight: null,
    pickup_date: null,
    urgency: 'normal',
    special_instructions: null,
    call_summary: 'Caller dropped off mid-call. Partial info captured.',
    transcript: 'Agent: Can you confirm your pickup city?\n[line disconnected]',
    recommended_action: 'Attempt callback within 1 hour.',
    missing_fields: [
      'caller_email',
      'company_name',
      'pickup_location',
      'load_type',
      'pickup_date',
    ],
    priority_score: 30,
    intake_status: 'incomplete',
    source: 'elevenlabs_dispatch_agent',
    assigned_to: null,
    elevenlabs_call_id: 'elv_call_006',
    make_execution_id: 'make_exec_006',
    call_timestamp: ago(30),
  },
];

export const MOCK_NOTES: InternalNote[] = [
  {
    id: 'note-1',
    intake_id: 'intake-002',
    note_text: 'Called ops manager — team drivers confirmed. Quote in flight.',
    created_at: ago(90),
    created_by: 'u-morgan',
    author: { full_name: 'Morgan Lee', email: 'morgan@dispatch.local' },
  },
  {
    id: 'note-2',
    intake_id: 'intake-003',
    note_text: 'Left voicemail. Will try again tomorrow morning.',
    created_at: ago(800),
    created_by: 'u-sam',
    author: { full_name: 'Sam Patel', email: 'sam@dispatch.local' },
  },
];

export const MOCK_ACTIVITY: ActivityLog[] = [
  {
    id: 'act-1',
    intake_id: 'intake-001',
    action_type: 'intake_created',
    action_detail: { source: 'elevenlabs_dispatch_agent' },
    created_at: ago(20),
    actor: null,
    actor_label: 'ElevenLabs · Make.com',
  },
  {
    id: 'act-2',
    intake_id: 'intake-002',
    action_type: 'intake_created',
    action_detail: null,
    created_at: ago(120),
    actor: null,
    actor_label: 'ElevenLabs · Make.com',
  },
  {
    id: 'act-3',
    intake_id: 'intake-002',
    action_type: 'assignment_changed',
    action_detail: { to: 'u-morgan' },
    created_at: ago(100),
    actor: 'demo-user',
    actor_label: 'Demo Dispatcher',
  },
  {
    id: 'act-4',
    intake_id: 'intake-003',
    action_type: 'status_changed',
    action_detail: { from: 'new', to: 'contacted' },
    created_at: ago(850),
    actor: 'u-sam',
    actor_label: 'Sam Patel',
  },
  {
    id: 'act-5',
    intake_id: 'intake-004',
    action_type: 'status_changed',
    action_detail: { from: 'contacted', to: 'quoted' },
    created_at: ago(200),
    actor: 'u-morgan',
    actor_label: 'Morgan Lee',
  },
];
